# Generated by Django 5.2.1 on 2025-05-21 00:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgenceImmo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('sigle', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('numeroCompte', models.CharField(blank=True, max_length=100)),
                ('ifu', models.CharField(blank=True, max_length=100)),
                ('logo', models.ImageField(blank=True, upload_to='logos/')),
                ('sup', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Commodite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('sup', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('sup', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('sup', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Maison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immat', models.CharField(max_length=100, unique=True)),
                ('loyer', models.IntegerField()),
                ('telDemarceur', models.CharField(blank=True, max_length=20)),
                ('quartier', models.CharField(max_length=255)),
                ('section', models.CharField(blank=True, max_length=100)),
                ('lot', models.IntegerField(blank=True, null=True)),
                ('parcelle', models.IntegerField(blank=True, null=True)),
                ('degLat', models.IntegerField()),
                ('minLat', models.IntegerField()),
                ('secLat', models.FloatField()),
                ('emisphere', models.CharField(max_length=1)),
                ('degLong', models.IntegerField()),
                ('minLong', models.IntegerField()),
                ('secLong', models.FloatField()),
                ('fuseau', models.CharField(max_length=1)),
                ('description', models.TextField(blank=True)),
                ('etat', models.CharField(choices=[('OCCUPEE', 'Occupée'), ('LIBRE', 'Libre')], default='LIBRE', max_length=10)),
                ('sup', models.BooleanField(default=False)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maisons', to='core.agenceimmo')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maisons', to='core.commune')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateEntre', models.DateField()),
                ('dateSortie', models.DateField(blank=True, null=True)),
                ('nomClient', models.CharField(max_length=100)),
                ('prenomClient', models.CharField(max_length=100)),
                ('telephoneClient', models.CharField(max_length=20)),
                ('numeroDocument', models.CharField(max_length=100)),
                ('dateEtabli', models.DateField()),
                ('dateExpi', models.DateField()),
                ('sup', models.BooleanField(default=False)),
                ('typeDocument', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='core.document')),
                ('maison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.maison')),
            ],
        ),
        migrations.CreateModel(
            name='CommoditeMaison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.IntegerField()),
                ('sup', models.BooleanField(default=False)),
                ('commodite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commodite_maisons', to='core.commodite')),
                ('maison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commodite_maisons', to='core.maison')),
            ],
        ),
        migrations.CreateModel(
            name='PaiementLoyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datePaiement', models.DateTimeField(default=django.utils.timezone.now)),
                ('numeroFacture', models.CharField(blank=True, max_length=100)),
                ('montant', models.IntegerField()),
                ('sup', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='core.location')),
            ],
        ),
        migrations.CreateModel(
            name='Penalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField()),
                ('sup', models.BooleanField(default=False)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalites', to='core.location')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoMaison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donnee', models.ImageField(upload_to='photos/')),
                ('libelle', models.CharField(blank=True, max_length=255)),
                ('sup', models.BooleanField(default=False)),
                ('maison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.maison')),
            ],
        ),
    ]
