# Generated by Django 5.2.1 on 2025-05-27 16:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgenceImmo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('immatriculation', models.CharField(max_length=10, unique=True)),
                ('ville', models.CharField(default='Ville inconnue', max_length=255)),
                ('quartier', models.CharField(blank=True, default='', max_length=255)),
                ('lien_google_maps', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='logos/')),
                ('sup', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Commodite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('sup', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('sup', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('numero', models.CharField(blank=True, max_length=100, null=True)),
                ('date_etablissement', models.DateField(blank=True, null=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('cloture', models.BooleanField(default=False)),
                ('sup', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Maison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immat', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('loyer', models.IntegerField()),
                ('quartier', models.CharField(blank=True, max_length=255, null=True)),
                ('google_maps', models.URLField(blank=True)),
                ('etat', models.CharField(choices=[('OCCUPEE', 'Occupée'), ('LIBRE', 'Libre')], default='LIBRE', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PaiementLoyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now)),
                ('numero_facture', models.CharField(blank=True, max_length=100, null=True)),
                ('montant', models.IntegerField(blank=True, null=True)),
                ('sup', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Penalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField()),
                ('sup', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoMaison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donnee', models.ImageField(upload_to='photos/')),
                ('libelle', models.CharField(blank=True, max_length=255)),
                ('sup', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('sup', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CommoditeMaison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.IntegerField()),
                ('sup', models.BooleanField(default=False)),
                ('commodite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commodite_maisons', to='core.commodite')),
            ],
        ),
    ]
