# Generated by Django 5.2.1 on 2025-05-27 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maison',
            name='agence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maisons', to='core.agenceimmo'),
        ),
        migrations.AddField(
            model_name='maison',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maisons', to='core.commune'),
        ),
        migrations.AddField(
            model_name='location',
            name='maison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.maison'),
        ),
        migrations.AddField(
            model_name='commoditemaison',
            name='maison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commodite_maisons', to='core.maison'),
        ),
        migrations.AddField(
            model_name='paiementloyer',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='core.location'),
        ),
        migrations.AddField(
            model_name='penalite',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalites', to='core.location'),
        ),
        migrations.AddField(
            model_name='photomaison',
            name='maison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.maison'),
        ),
        migrations.AddField(
            model_name='location',
            name='type_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='core.typedocument'),
        ),
    ]
