# Generated by Django 5.2.1 on 2025-05-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maison',
            name='sup',
            field=models.BooleanField(default=False),
        ),
    ]
