# Generated by Django 4.2.16 on 2025-06-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('date_naissance', models.DateField()),
                ('profession', models.CharField(max_length=100)),
                ('revenus_mensuels', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adresse_actuelle', models.TextField()),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('statut_actif', models.BooleanField(default=True)),
            ],
        ),
    ]
