# Generated by Django 4.2.16 on 2025-06-15 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maison', '0001_initial'),
        ('proprietaire', '0001_initial'),
        ('agence', '0001_initial'),
        ('locataire', '0001_initial'),
        ('souscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('loyer_mensuel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charges_mensuelles', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depot_garantie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('resilie', 'Résilié'), ('termine', 'Terminé'), ('suspendu', 'Suspendu')], default='actif', max_length=50)),
                ('date_signature', models.DateTimeField(auto_now_add=True)),
                ('document_contrat', models.FileField(blank=True, null=True, upload_to='contrats/')),
                ('conditions_particulieres', models.TextField(blank=True)),
                ('agence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='agence.agence')),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locataire.locataire')),
                ('maison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maison.maison')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proprietaire.proprietaire')),
                ('souscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='souscription.souscription')),
            ],
        ),
    ]
