# Generated by Django 4.2.16 on 2025-06-13 16:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agence',
            name='employes',
            field=models.ManyToManyField(blank=True, related_name='agences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agence',
            name='siret',
            field=models.CharField(max_length=20),
        ),
    ]
