# Generated by Django 4.2.16 on 2025-06-15 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maison', '0001_initial'),
        ('locataire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Souscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('message_locataire', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('annulee', 'Annulée')], default='en_attente', max_length=50)),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('commentaire_agence', models.TextField(blank=True)),
                ('documents_fournis', models.JSONField(default=dict)),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locataire.locataire')),
                ('maison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maison.maison')),
            ],
        ),
    ]
