# Generated by Django 5.2.1 on 2025-06-09 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proprietaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('adresse_complete', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('nombre_pieces', models.IntegerField()),
                ('surface', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_bien', models.CharField(choices=[('appartement', 'Appartement'), ('maison', 'Maison'), ('studio', 'Studio')], max_length=50)),
                ('loyer_mensuel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depot_garantie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meuble', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('loue', 'Loué'), ('maintenance', 'En maintenance'), ('hors_service', 'Hors service')], default='disponible', max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proprietaire.proprietaire')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='maison_photos/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('maison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='maison.maison')),
            ],
        ),
    ]
