# Generated by Django 4.2.16 on 2025-06-13 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0002_agence_employes_alter_agence_siret'),
        ('maison', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maison',
            name='agence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maisons', to='agence.agence'),
        ),
    ]
