# Generated by Django 4.2.16 on 2025-06-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField()),
                ('date_naissance', models.DateField()),
                ('piece_identite', models.FileField(blank=True, null=True, upload_to='proprietaire_docs/')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('statut_actif', models.BooleanField(default=True)),
            ],
        ),
    ]
